# Generated by Django 3.1 on 2021-04-17 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='survey',
            name='name',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey_question_text',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='surveyquestionalternative',
            name='survey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AddField(
            model_name='surveyquestionalternative',
            name='survey_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyquestionalternative',
            name='survey_question_alternative_text',
            field=models.CharField(default=None, max_length=256),
        ),
        migrations.AddField(
            model_name='surveyuseranswer',
            name='survey',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AddField(
            model_name='surveyuseranswer',
            name='survey_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion'),
        ),
        migrations.AddField(
            model_name='surveyuseranswer',
            name='survey_question_alternative',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestionalternative'),
        ),
        migrations.AddField(
            model_name='surveyuseranswer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
